name: Playwright Tests
on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies for client
      run: npm install -g pnpm && pnpm install --no-frozen-lockfile
      working-directory: ./apps/client
    - name: Install Playwright Browsers for client
      run: pnpm exec playwright install --with-deps
      working-directory: ./apps/client
    - name: Run Playwright tests for client
      run: pnpm exec playwright test
      working-directory: ./apps/client
      env: 
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-client
        path: apps/client/playwright-report
        retention-days: 30
    - name: Install dependencies for server
      run: npm install -g pnpm && pnpm install --no-frozen-lockfile
      working-directory: ./apps/server
    - name: Install Playwright Browsers for server
      run: pnpm exec playwright install --with-deps
      working-directory: ./apps/server
    - name: Run Playwright tests for server
      run: pnpm exec playwright test
      working-directory: ./apps/server
      env: 
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-server
        path: apps/server/playwright-report
        retention-days: 30
